#!/bin/sh

if [ ! -e /etc/rootpt-resize ] && \
    type parted > /dev/null && \
    lock -n /var/lock/root-resize; then
    ROOT_BLK="$(readlink -f "/sys/dev/block/$(awk -e '$9=="/dev/root"{print $3}' /proc/self/mountinfo)")"
    ROOT_DISK="/dev/$(basename "${ROOT_BLK%/*}")"
    ROOT_PART="${ROOT_BLK##*[^0-9]}"

    echo "resize $ROOT_DISK $ROOT_PART"

    parted -s "${ROOT_DISK}" resizepart "${ROOT_PART}" 100%
    mount_root done
    touch /etc/rootpt-resize
    reboot
fi
exit 1
